name = "api"
main = "src/index.ts"
compatibility_date = "2025-08-20"

[observability]
enabled = true
head_sampling_rate = 1

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"

simple = { limit = 5, period = 60 }
