name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy Project Artifacts to Vercel and Set Preview URL
      #   id: deploy
      #   run: |
      #     DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
      #     echo "Raw deployment URL: '$DEPLOYMENT_URL'"
      #     if [ -z "$DEPLOYMENT_URL" ]; then
      #       echo "ERROR: Deployment URL is empty!"
      #       exit 1
      #     fi
      #     # Test without secret first
      #     echo "Deployment URL: $DEPLOYMENT_URL"
      #     echo "Testing URL without secret: $DEPLOYMENT_URL"
      #     # Clear any existing output and set fresh output
      #     echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
      #     echo "Output file after writing:"
      #     cat $GITHUB_OUTPUT

      # For Turborepo monorepo - install dependencies at root
      - name: Install dependencies
        run: npm ci

      # Wait for deployment to be fully ready (optional but recommended)
      - name: Start the NextJS Server
        working-directory: apps/web
        run: |
          npm run build
          npm run start
          npx cypress run --config baseUrl=http://localhost:3000
