name: (Staging) CI/CD Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        working-directory: apps/web
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: cd apps/web && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: cd apps/web && vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Get Vercel .env
        run: cd apps/web && vercel env pull .env --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: cd apps/web && npm run build
          start: cd apps/web && npm run start
          wait-on: 'http://localhost:3000'

      - name: Deploy To Vercel Preview
        run: cd apps/web && vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
